### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by buschmann23** [cutelyst/asql#6]
When trying to compile the current code, I get the following error: (ok, it is the linker, not the compiler)

```
[   61s] [ 71%] Linking CXX shared library libASqlQt6Pg.so
[   61s] cd "/home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/build/src" && /usr/bin/cmake -E cmake_link_script CMakeFiles/ASqlQt6Pg.dir/link.txt --verbose=1
[   61s] /usr/bin/c++ -fPIC -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG -O2 -g -DNDEBUG -flto=auto -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -shared -Wl,-soname,libASqlQt6Pg.so.0 -o libASqlQt6Pg.so.0.50.0 CMakeFiles/ASqlQt6Pg.dir/ASqlQt6Pg_autogen/mocs_compilation.cpp.o CMakeFiles/ASqlQt6Pg.dir/adriverpg.cpp.o CMakeFiles/ASqlQt6Pg.dir/apg.cpp.o  /usr/lib64/libQt6Core.so.6.2.1 /usr/lib64/libpq.so 
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `AResultPg::~AResultPg()':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:735: undefined reference to `AResultPrivate::~AResultPrivate()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `std::_Function_handler<void (AResult&), ADriverPg::unsubscribeFromNotification(std::shared_ptr<ADriver> const&, QString const&)::{lambda(AResult&)#1}>::_M_invoke(std::_Any_data const&, AResult&)':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:422: undefined reference to `AResult::error() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o:/home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:422: undefined reference to `AResult::errorString() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `ADriverPg::open(std::function<void (bool, QString const&)>)':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:99: undefined reference to `ADriver::connectionInfo() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:101: undefined reference to `ADriver::connectionInfo() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `ADriverPg::~ADriverPg()':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriver.h:26: undefined reference to `vtable for ADriver'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `std::_Function_handler<void (AResult&), ADriverPg::subscribeToNotification(std::shared_ptr<ADriver> const&, QString const&, std::function<void (ADatabaseNotification const&)>, QObject*)::{lambda(AResult&)#1}>::_M_invoke(std::_Any_data const&, AResult&)':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:402: undefined reference to `AResult::error() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o:/home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:402: undefined reference to `AResult::errorString() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o:/home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:403: undefined reference to `AResult::error() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `APGQuery::done()':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.h:77: undefined reference to `AResult::AResult(std::shared_ptr<AResultPrivate> const&)'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.h:81: undefined reference to `AResult::~AResult()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `ADriverPg::doExec(APGQuery&)':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:484: undefined reference to `APreparedQuery::identification() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:486: undefined reference to `APreparedQuery::identification() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:499: undefined reference to `APreparedQuery::query() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:498: undefined reference to `APreparedQuery::identification() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `ADriverPg::doExecParams(APGQuery&)':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:662: undefined reference to `APreparedQuery::identification() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:664: undefined reference to `APreparedQuery::identification() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:677: undefined reference to `APreparedQuery::query() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:676: undefined reference to `APreparedQuery::identification() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `ADriverPg::exec(std::shared_ptr<ADriver> const&, QString const&, QList<QVariant> const&, std::function<void (AResult&)>, QObject*)':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.h:63: undefined reference to `APreparedQuery::APreparedQuery()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `ADriverPg::exec(std::shared_ptr<ADriver> const&, QStringView, QList<QVariant> const&, std::function<void (AResult&)>, QObject*)':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.h:63: undefined reference to `APreparedQuery::APreparedQuery()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `ADriverPg::exec(std::shared_ptr<ADriver> const&, APreparedQuery const&, QList<QVariant> const&, std::function<void (AResult&)>, QObject*)':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.h:63: undefined reference to `APreparedQuery::APreparedQuery()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `ADriverPg::open(std::function<void (bool, QString const&)>)::{lambda()#3}::operator()() const [clone .lto_priv.0]':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:200: undefined reference to `APreparedQuery::identification() const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `AResultPg::~AResultPg()':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:735: undefined reference to `AResultPrivate::~AResultPrivate()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:735: undefined reference to `AResultPrivate::~AResultPrivate()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `ADriverPg::qt_metacast(char const*)':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/build/src/ASqlQt6Pg_autogen/include/moc_adriverpg.cpp:89: undefined reference to `ADriver::qt_metacast(char const*)'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `ADriverPg::qt_metacall(QMetaObject::Call, int, void**)':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/build/src/ASqlQt6Pg_autogen/include/moc_adriverpg.cpp:94: undefined reference to `ADriver::qt_metacall(QMetaObject::Call, int, void**)'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o: in function `APGQuery::done()':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.h:81: undefined reference to `AResult::~AResult()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o:(.data.rel.ro+0x38): undefined reference to `typeinfo for AResultPrivate'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o:(.data.rel.ro+0x68): undefined reference to `typeinfo for ADriver'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o:(.data.rel.ro+0xa0): undefined reference to `ADriver::staticMetaObject'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o:(.data.rel.ro+0x128): undefined reference to `AResultPrivate::indexOfField(QString const&) const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans0.ltrans.o:(.data.rel.ro+0x130): undefined reference to `AResultPrivate::indexOfField(QStringView) const'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans1.ltrans.o: in function `APg::createRawDriver() const':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:54: undefined reference to `ADriver::ADriver(QString const&)'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans1.ltrans.o: in function `APg::createDriver() const':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:54: undefined reference to `ADriver::ADriver(QString const&)'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans1.ltrans.o: in function `APg::createDatabase() const':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:54: undefined reference to `ADriver::ADriver(QString const&)'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans1.ltrans.o: in function `APg::createDatabase() const':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/apg.cpp:51: undefined reference to `ADatabase::ADatabase(std::shared_ptr<ADriver> const&)'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans1.ltrans.o: in function `APg::APg(QString const&)':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/apg.cpp:15: undefined reference to `ADriverFactory::ADriverFactory()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans1.ltrans.o: in function `APg::database(QString const&)':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/apg.cpp:33: undefined reference to `ADatabase::ADatabase(std::shared_ptr<ADriverFactory> const&)'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans1.ltrans.o: in function `std::_Sp_counted_ptr_inplace<AResultPg, std::allocator<AResultPg>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:735: undefined reference to `AResultPrivate::~AResultPrivate()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans1.ltrans.o:/home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/adriverpg.cpp:735: undefined reference to `AResultPrivate::~AResultPrivate()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans1.ltrans.o: in function `APg::~APg() [clone .localalias]':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/apg.cpp:23: undefined reference to `ADriverFactory::~ADriverFactory()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans1.ltrans.o: in function `std::_Sp_counted_ptr_inplace<APg, std::allocator<APg>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()':
[   61s] /home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/src/apg.cpp:23: undefined reference to `ADriverFactory::~ADriverFactory()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans1.ltrans.o: in function `APg::APg(QString const&)':
[   61s] /usr/include/c++/11/ext/new_allocator.h:145: undefined reference to `ADriverFactory::~ADriverFactory()'
[   61s] /usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: /tmp/ccsiGsMc.ltrans1.ltrans.o:(.data.rel.ro+0x40): undefined reference to `typeinfo for ADriverFactory'
[   61s] collect2: error: ld returned 1 exit status
[   61s] make[2]: *** [src/CMakeFiles/ASqlQt6Pg.dir/build.make:134: src/libASqlQt6Pg.so.0.50.0] Error 1
[   61s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/asql-0.50.60~git1637889808.c43b1d2/build'
[   61s] make[1]: *** [CMakeFiles/Makefile2:136: src/CMakeFiles/ASqlQt6Pg.dir/all] Error 2
[   61s] make[1]: *** Waiting for unfinished jobs....
```

**Comment by dantti** [comment]
hmm does it build with Qt6 fine? I didn't test this last version with Qt6...

**Comment by buschmann23** [comment]
No, same issue. Last version I tried was 0.43 - that worked.

**Comment by dantti** [comment]
is this gold linker or something, works fine on Ubuntu 20.04 and 21.10

**Comment by dantti** [comment]
hmm I think I'm missing the exports for the classes

**Comment by dantti** [comment]
please test

**Comment by buschmann23** [comment]
Yes, that fixed it. :) 👍🏻
